import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "../components/ui/sonner";
import { ThemeProvider } from "../components/theme-provider";
import { AuthProvider } from "../contexts/auth-context";

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://connect.hsannu.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="//connect.hsannu.com" />
      </head>
      <body className="antialiased">
        <ThemeProvider>
          <AuthProvider>
          {children}
          <Toaster position="bottom-right" closeButton />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
